### ISSUE TITLE
When the first release?

### ISSUE THREAD

**Issue by BoghosDavtyan** [Bernard-Borg/SoundboardApp#2]
When do you think you are going to release the first release of this project?

**Comment by Bernard-Borg** [comment]
I was recently converting it from electron to tauri. Recently, I've been trying to make it so that it can play sounds without having to  focus on the window (through Rust). I might just release an early alpha if you want to try out the current state of the application. Even so, I'm having trouble with the production build of the project (but it works in development). I'm looking into it.

**Comment by Bernard-Borg** [comment]
An alpha version has been released. You can test this if you'd like :)
